#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EmergencyAmbulance_AndroidCSharp.Resource", IsApplication=true)]

namespace EmergencyAmbulance_AndroidCSharp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int ambulance_array = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int sexo = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int tipo_sangre = 2131034114;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int theme_devicedefault_background = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08001b
			public const int btnGuardar = 2131230747;
			
			// aapt resource value: 0x7f080006
			public const int button1 = 2131230726;
			
			// aapt resource value: 0x7f080001
			public const int editText1 = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int editText2 = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int editText3 = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int spinner1 = 2131230727;
			
			// aapt resource value: 0x7f08000c
			public const int spinner2 = 2131230732;
			
			// aapt resource value: 0x7f080018
			public const int spinner3 = 2131230744;
			
			// aapt resource value: 0x7f080000
			public const int textView1 = 2131230720;
			
			// aapt resource value: 0x7f080017
			public const int textView10 = 2131230743;
			
			// aapt resource value: 0x7f080019
			public const int textView11 = 2131230745;
			
			// aapt resource value: 0x7f080011
			public const int textView12 = 2131230737;
			
			// aapt resource value: 0x7f080015
			public const int textView13 = 2131230741;
			
			// aapt resource value: 0x7f080002
			public const int textView2 = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int textView3 = 2131230724;
			
			// aapt resource value: 0x7f080009
			public const int textView4 = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int textView6 = 2131230731;
			
			// aapt resource value: 0x7f08000d
			public const int textView7 = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int textView8 = 2131230735;
			
			// aapt resource value: 0x7f080013
			public const int textView9 = 2131230739;
			
			// aapt resource value: 0x7f08000a
			public const int txtApellido = 2131230730;
			
			// aapt resource value: 0x7f08001a
			public const int txtDiagnostico = 2131230746;
			
			// aapt resource value: 0x7f08000e
			public const int txtEdad = 2131230734;
			
			// aapt resource value: 0x7f080008
			public const int txtNombre = 2131230728;
			
			// aapt resource value: 0x7f080010
			public const int txtPresion1 = 2131230736;
			
			// aapt resource value: 0x7f080012
			public const int txtPresion2 = 2131230738;
			
			// aapt resource value: 0x7f080014
			public const int txtPulso1 = 2131230740;
			
			// aapt resource value: 0x7f080016
			public const int txtPulso2 = 2131230742;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int ThemeCustom = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
